image: javiersantos/android-ci:28.0.3

before_script:
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/

stages:
  - build
  - test
  - code-analysis

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test

lint:
  stage: code-analysis
  script:
    ./gradlew lint
  allow_failure: true

checkstyle:
  stage: code-analysis
  script:
    ./gradlew checkstyle
  allow_failure: true

pmd:
  stage: code-analysis
  script:
    ./gradlew pmd
  allow_failure: true

